/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesMerchantRouteImport } from './routes/opportunities.merchant'
import { Route as OpportunitiesInvestorRouteImport } from './routes/opportunities.investor'
import { Route as OpportunitiesConsumerRouteImport } from './routes/opportunities.consumer'
import { Route as OpportunitiesCareerRouteImport } from './routes/opportunities.career'
import { Route as AboutVisionRouteImport } from './routes/about.vision'
import { Route as AboutPhilosophyRouteImport } from './routes/about.philosophy'
import { Route as AboutMissionRouteImport } from './routes/about.mission'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesMerchantRoute = OpportunitiesMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const OpportunitiesInvestorRoute = OpportunitiesInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const OpportunitiesConsumerRoute = OpportunitiesConsumerRouteImport.update({
  id: '/consumer',
  path: '/consumer',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const OpportunitiesCareerRoute = OpportunitiesCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const AboutVisionRoute = AboutVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => AboutRoute,
} as any)
const AboutPhilosophyRoute = AboutPhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => AboutRoute,
} as any)
const AboutMissionRoute = AboutMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/services': typeof ServicesRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/philosophy': typeof AboutPhilosophyRoute
  '/about/vision': typeof AboutVisionRoute
  '/opportunities/career': typeof OpportunitiesCareerRoute
  '/opportunities/consumer': typeof OpportunitiesConsumerRoute
  '/opportunities/investor': typeof OpportunitiesInvestorRoute
  '/opportunities/merchant': typeof OpportunitiesMerchantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/services': typeof ServicesRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/philosophy': typeof AboutPhilosophyRoute
  '/about/vision': typeof AboutVisionRoute
  '/opportunities/career': typeof OpportunitiesCareerRoute
  '/opportunities/consumer': typeof OpportunitiesConsumerRoute
  '/opportunities/investor': typeof OpportunitiesInvestorRoute
  '/opportunities/merchant': typeof OpportunitiesMerchantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/services': typeof ServicesRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/philosophy': typeof AboutPhilosophyRoute
  '/about/vision': typeof AboutVisionRoute
  '/opportunities/career': typeof OpportunitiesCareerRoute
  '/opportunities/consumer': typeof OpportunitiesConsumerRoute
  '/opportunities/investor': typeof OpportunitiesInvestorRoute
  '/opportunities/merchant': typeof OpportunitiesMerchantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/opportunities'
    | '/services'
    | '/about/mission'
    | '/about/philosophy'
    | '/about/vision'
    | '/opportunities/career'
    | '/opportunities/consumer'
    | '/opportunities/investor'
    | '/opportunities/merchant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/opportunities'
    | '/services'
    | '/about/mission'
    | '/about/philosophy'
    | '/about/vision'
    | '/opportunities/career'
    | '/opportunities/consumer'
    | '/opportunities/investor'
    | '/opportunities/merchant'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/opportunities'
    | '/services'
    | '/about/mission'
    | '/about/philosophy'
    | '/about/vision'
    | '/opportunities/career'
    | '/opportunities/consumer'
    | '/opportunities/investor'
    | '/opportunities/merchant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/merchant': {
      id: '/opportunities/merchant'
      path: '/merchant'
      fullPath: '/opportunities/merchant'
      preLoaderRoute: typeof OpportunitiesMerchantRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/opportunities/investor': {
      id: '/opportunities/investor'
      path: '/investor'
      fullPath: '/opportunities/investor'
      preLoaderRoute: typeof OpportunitiesInvestorRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/opportunities/consumer': {
      id: '/opportunities/consumer'
      path: '/consumer'
      fullPath: '/opportunities/consumer'
      preLoaderRoute: typeof OpportunitiesConsumerRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/opportunities/career': {
      id: '/opportunities/career'
      path: '/career'
      fullPath: '/opportunities/career'
      preLoaderRoute: typeof OpportunitiesCareerRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/about/vision': {
      id: '/about/vision'
      path: '/vision'
      fullPath: '/about/vision'
      preLoaderRoute: typeof AboutVisionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/philosophy': {
      id: '/about/philosophy'
      path: '/philosophy'
      fullPath: '/about/philosophy'
      preLoaderRoute: typeof AboutPhilosophyRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/mission': {
      id: '/about/mission'
      path: '/mission'
      fullPath: '/about/mission'
      preLoaderRoute: typeof AboutMissionRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutMissionRoute: typeof AboutMissionRoute
  AboutPhilosophyRoute: typeof AboutPhilosophyRoute
  AboutVisionRoute: typeof AboutVisionRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutMissionRoute: AboutMissionRoute,
  AboutPhilosophyRoute: AboutPhilosophyRoute,
  AboutVisionRoute: AboutVisionRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface OpportunitiesRouteChildren {
  OpportunitiesCareerRoute: typeof OpportunitiesCareerRoute
  OpportunitiesConsumerRoute: typeof OpportunitiesConsumerRoute
  OpportunitiesInvestorRoute: typeof OpportunitiesInvestorRoute
  OpportunitiesMerchantRoute: typeof OpportunitiesMerchantRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesCareerRoute: OpportunitiesCareerRoute,
  OpportunitiesConsumerRoute: OpportunitiesConsumerRoute,
  OpportunitiesInvestorRoute: OpportunitiesInvestorRoute,
  OpportunitiesMerchantRoute: OpportunitiesMerchantRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
